package anki:addon;

// The interface that the addon host implements (Anki rustlib)
interface host {
    log: func(message: string);
}

// The interface that the addon guest implements (addon code)
interface guest {
    use decks.{deck-id};
    use notes.{note};

    record addon-manifest {
        // The name of the addon
        name: string,

        // Requested entries in the Tools menu (list of labels)
        tool-menu-entries: list<string>,
    }

    // This will be called after the addon host has loaded the addon
    init: func() -> addon-manifest;

    // GUI Callbacks
    on-tool-menu-entry-clicked: func(idx: u32);

    // Hooks
    before-add-note: func(note: note, did: deck-id) -> option<note>;
}

world addon {
    import host;
    export guest;
}
